const ejs = require('ejs');
const fs = require('fs-extra');
const path = require('path');

async function renderToDir(ir, outDir, options) {
  await fs.ensureDir(outDir);
  
  const templateDir = path.resolve(__dirname, '../../../templates', options.template);
  
  if (!fs.existsSync(templateDir)) {
    throw new Error(`Template not found: ${options.template}`);
  }
  
  await copyTemplateBase(templateDir, outDir);
  
  await renderPackageJson(outDir, ir, options);
  
  await renderAppFile(outDir, ir, options);
  
  await renderIndexPage(outDir, ir, options);
  
  for (const instruction of ir.instructions) {
    await renderInstructionPage(outDir, instruction, ir, options, templateDir);
  }
  
  await renderLibFiles(outDir, ir, options);
}

async function copyTemplateBase(templateDir, outDir) {
  const filesToCopy = [
    'next.config.js',
    'tsconfig.json',
    'tailwind.config.js',
    'postcss.config.js',
    'components',
    'styles',
    'public'
  ];
  
  for (const file of filesToCopy) {
    const srcPath = path.join(templateDir, file);
    const destPath = path.join(outDir, file);
    
    if (await fs.pathExists(srcPath)) {
      await fs.copy(srcPath, destPath, { overwrite: true });
    }
  }
}

async function renderPackageJson(outDir, ir, options) {
  const packageJson = {
    name: ir.programName.replace(/_/g, '-'),
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev -p 5000',
      build: 'next build',
      start: 'next start -p 5000',
      lint: 'next lint'
    },
    dependencies: {
      'next': '^14.0.0',
      'react': '^18.2.0',
      'react-dom': '^18.2.0',
      '@solana/web3.js': '^1.95.0',
      '@solana/wallet-adapter-base': '^0.9.23',
      '@solana/wallet-adapter-react': '^0.15.35',
      '@solana/wallet-adapter-react-ui': '^0.9.35',
      '@solana/wallet-adapter-wallets': '^0.19.32',
      '@coral-xyz/anchor': '^0.30.1'
    },
    devDependencies: {
      '@types/node': '^20.0.0',
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      'typescript': '^5.0.0',
      'autoprefixer': '^10.4.16',
      'postcss': '^8.4.31',
      'tailwindcss': '^3.3.5'
    }
  };
  
  await fs.outputJSON(path.join(outDir, 'package.json'), packageJson, { spaces: 2 });
}

async function renderAppFile(outDir, ir, options) {
  const content = `import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { useMemo } from 'react';
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
import { PhantomWalletAdapter } from '@solana/wallet-adapter-wallets';
import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
import { clusterApiUrl } from '@solana/web3.js';

require('@solana/wallet-adapter-react-ui/styles.css');

export default function App({ Component, pageProps }: AppProps) {
  const network = WalletAdapterNetwork.${options.network.charAt(0).toUpperCase() + options.network.slice(1)};
  const endpoint = useMemo(() => clusterApiUrl(network), [network]);
  
  const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
    ],
    []
  );

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect>
        <WalletModalProvider>
          <Component {...pageProps} />
        </WalletModalProvider>
      </WalletProvider>
    </ConnectionProvider>
  );
}
`;
  
  await fs.outputFile(path.join(outDir, 'pages', '_app.tsx'), content);
}

async function renderIndexPage(outDir, ir, options) {
  const content = `import Head from 'next/head';
import Link from 'next/link';
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui';

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800">
      <Head>
        <title>${ir.programName} - CastUI Generated</title>
        <meta name="description" content="Generated by CastUI" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="border-b border-gray-700 bg-gray-900/50 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold text-white">${ir.programName}</h1>
            <WalletMultiButton />
          </div>
        </div>
      </nav>

      <main className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <div className="bg-gray-800 rounded-lg shadow-xl p-8 border border-gray-700">
            <h2 className="text-3xl font-bold text-white mb-4">
              Welcome to ${ir.programName}
            </h2>
            <p className="text-gray-300 mb-6">
              This UI was automatically generated by CastUI from your Anchor IDL.
            </p>
            
            <div className="bg-gray-900 rounded-lg p-4 mb-6">
              <p className="text-sm text-gray-400 mb-2">Program ID:</p>
              <code className="text-sm text-green-400 font-mono">${ir.programId}</code>
            </div>

            <div className="mb-6">
              <h3 className="text-xl font-semibold text-white mb-4">Available Instructions</h3>
              <div className="grid gap-3">
                ${ir.instructions.map(instr => `
                <Link href="/instruction/${instr.name}">
                  <div className="bg-gray-900 hover:bg-gray-700 transition-colors rounded-lg p-4 cursor-pointer border border-gray-600 hover:border-blue-500">
                    <h4 className="font-semibold text-white mb-1">${instr.name}</h4>
                    ${instr.docs ? `<p className="text-sm text-gray-400">${instr.docs.split('\n')[0]}</p>` : ''}
                  </div>
                </Link>
                `).join('')}
              </div>
            </div>

            <div className="text-sm text-gray-500 text-center pt-6 border-t border-gray-700">
              Generated by <span className="text-blue-400">CastUI</span> • Network: <span className="text-green-400">${options.network}</span>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
`;
  
  await fs.outputFile(path.join(outDir, 'pages', 'index.tsx'), content);
}

async function renderInstructionPage(outDir, instruction, ir, options, templateDir) {
  const templatePath = path.join(templateDir, 'pages', 'instruction.ejs');
  
  let content;
  
  if (await fs.pathExists(templatePath)) {
    const template = await fs.readFile(templatePath, 'utf8');
    content = ejs.render(template, { instruction, programName: ir.programName, programId: ir.programId });
  } else {
    content = generateInstructionPageContent(instruction, ir);
  }
  
  await fs.outputFile(
    path.join(outDir, 'pages', 'instruction', `${instruction.name}.tsx`),
    content
  );
}

function generateInstructionPageContent(instruction, ir) {
  return `import { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useConnection, useWallet } from '@solana/wallet-adapter-react';
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import { PublicKey, Transaction } from '@solana/web3.js';

export default function ${toPascalCase(instruction.name)}Page() {
  const { connection } = useConnection();
  const { publicKey, sendTransaction } = useWallet();
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string>('');
  
  ${instruction.args.map(arg => {
    const initialValue = arg.uiType === 'Toggle' ? 'false' : (arg.uiType === 'Number' || arg.uiType === 'BigInt' ? '0' : "''");
    return `const [${arg.name}, set${toPascalCase(arg.name)}] = useState(${initialValue});`;
  }).join('\n  ')}

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!publicKey) {
      setResult('Please connect your wallet first');
      return;
    }
    
    setLoading(true);
    setResult('');
    
    try {
      setResult('Instruction execution would happen here. Connect to your Anchor program.');
    } catch (error: any) {
      setResult(\`Error: \${error.message}\`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800">
      <Head>
        <title>${instruction.name} - ${ir.programName}</title>
      </Head>

      <nav className="border-b border-gray-700 bg-gray-900/50 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href="/" className="text-blue-400 hover:text-blue-300">
                ← Back
              </Link>
              <h1 className="text-2xl font-bold text-white">${instruction.name}</h1>
            </div>
            <WalletMultiButton />
          </div>
        </div>
      </nav>

      <main className="container mx-auto px-4 py-12">
        <div className="max-w-2xl mx-auto">
          <div className="bg-gray-800 rounded-lg shadow-xl p-8 border border-gray-700">
            ${instruction.docs ? `
            <div className="mb-6 bg-blue-900/20 border border-blue-800 rounded-lg p-4">
              <p className="text-blue-300 text-sm">${instruction.docs}</p>
            </div>
            ` : ''}

            <form onSubmit={handleSubmit} className="space-y-6">
              ${instruction.args.map(arg => generateFormField(arg)).join('\n              ')}
              
              ${instruction.accounts.length > 0 ? `
              <div className="border-t border-gray-700 pt-6">
                <h3 className="text-lg font-semibold text-white mb-3">Accounts</h3>
                <div className="space-y-2">
                  ${instruction.accounts.map(acc => `
                  <div className="bg-gray-900 rounded p-3">
                    <div className="flex items-center justify-between">
                      <span className="text-gray-300 font-mono text-sm">${acc.name}</span>
                      <div className="flex gap-2">
                        ${acc.isSigner ? '<span className="text-xs bg-yellow-900 text-yellow-300 px-2 py-1 rounded">signer</span>' : ''}
                        ${acc.isWritable ? '<span className="text-xs bg-red-900 text-red-300 px-2 py-1 rounded">writable</span>' : ''}
                      </div>
                    </div>
                  </div>
                  `).join('')}
                </div>
              </div>
              ` : ''}

              <button
                type="submit"
                disabled={!publicKey || loading}
                className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-semibold py-3 px-6 rounded-lg transition-colors"
              >
                {loading ? 'Processing...' : 'Execute Instruction'}
              </button>
            </form>

            {result && (
              <div className="mt-6 bg-gray-900 border border-gray-700 rounded-lg p-4">
                <pre className="text-sm text-gray-300 whitespace-pre-wrap">{result}</pre>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
`;
}

function generateFormField(arg) {
  const label = arg.name.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  const inputType = getInputType(arg.uiType);
  const pascalName = toPascalCase(arg.name);
  
  if (arg.uiType === 'Toggle') {
    return `<div className="flex items-center gap-3">
                <input
                  type="checkbox"
                  id="${arg.name}"
                  checked={${arg.name}}
                  onChange={(e) => set${pascalName}(e.target.checked)}
                  className="w-5 h-5 bg-gray-900 border border-gray-600 rounded focus:ring-2 focus:ring-blue-500"
                />
                <label htmlFor="${arg.name}" className="text-sm font-medium text-gray-300">
                  ${label} ${arg.required ? '<span className="text-red-400">*</span>' : ''}
                </label>
              </div>`;
  }
  
  return `<div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  ${label} ${arg.required ? '<span className="text-red-400">*</span>' : ''}
                </label>
                <input
                  type="${inputType}"
                  value={${arg.name}}
                  onChange={(e) => set${pascalName}(${inputType === 'number' ? 'Number(e.target.value)' : 'e.target.value'})}
                  ${arg.required ? 'required' : ''}
                  className="w-full bg-gray-900 border border-gray-600 rounded-lg px-4 py-2 text-white focus:outline-none focus:border-blue-500"
                  placeholder="${getPlaceholder(arg)}"
                />
              </div>`;
}

function getInputType(uiType) {
  switch (uiType) {
    case 'Number':
    case 'BigInt':
      return 'number';
    case 'Toggle':
      return 'checkbox';
    default:
      return 'text';
  }
}

function getPlaceholder(arg) {
  switch (arg.uiType) {
    case 'Address':
      return 'Enter Solana address (base58)';
    case 'Number':
    case 'BigInt':
      return 'Enter number';
    default:
      return `Enter ${arg.name}`;
  }
}

function toPascalCase(str) {
  return str.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('');
}

async function renderLibFiles(outDir, ir, options) {
  const anchorClientContent = `import { Program, AnchorProvider, setProvider } from '@coral-xyz/anchor';
import { Connection, PublicKey } from '@solana/web3.js';

export function getProvider(connection: Connection, wallet: any) {
  const provider = new AnchorProvider(connection, wallet, {
    preflightCommitment: 'processed',
  });
  setProvider(provider);
  return provider;
}

export const PROGRAM_ID = new PublicKey('${ir.programId}');
`;
  
  await fs.outputFile(path.join(outDir, 'lib', 'anchorClient.ts'), anchorClientContent);
  
  const pdaHelpersContent = `import { PublicKey } from '@solana/web3.js';
import { PROGRAM_ID } from './anchorClient';

export async function derivePDA(seeds: (Buffer | Uint8Array)[]): Promise<[PublicKey, number]> {
  return PublicKey.findProgramAddress(seeds, PROGRAM_ID);
}
`;
  
  await fs.outputFile(path.join(outDir, 'lib', 'pdaHelpers.ts'), pdaHelpersContent);
}

module.exports = { renderToDir };
